;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        ivy-done
        kill-region
        org-self-insert-command
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-M-x
        hydra-muti-cursor/mc/mark-next-like-this
        hydra-muti-cursor/mc/mark-previous-like-this
        ))
