# Disable access control
# xhost +SI:localuser:$USER

# Themes, etc
# gnome-settings-daemon &

# Fallback cursor
xsetroot -cursor_name left_ptr

setxkbmap -option ctrl:nocaps

# Keyboard repeat rate
xset r rate 200 60

# export ssh auth socket
export SSH_AUTH_SOCK="$(journalctl --user -u gpg-agent -b | grep -Eo 'ssh socket \((/[^/]+)+\.ssh' | tail -1 | sed 's/ssh socket (//')"

# start lemonbar
while true; do $HOME/.emacs.d/exwm/bin/lemonbar-data; done | lemonbar -b -f "Input Sans:size=8" -f "Font Awesome" -B "#2c2c2c" -F "#dcdccc" &

# Start Emacs
exec dbus-launch --exit-with-session emacs