# Disable access control
# xhost +SI:localuser:$USER

# Themes, etc
# gnome-settings-daemon &

# Fallback cursor
xsetroot -cursor_name left_ptr

setxkbmap -option ctrl:nocaps

# Keyboard repeat rate
# xset r rate 200 60

# export ssh auth socket
export SSH_AUTH_SOCK="$(journalctl --user -u gpg-agent -b | grep -Eo 'ssh socket \((/[^/]+)+\.ssh' | tail -1 | sed 's/ssh socket (//')"

# turn on numlock
numlockx &

# start lemonbar
$HOME/.emacs.d/exwm/bin/start-bar &

# Start Emacs
exec dbus-launch --exit-with-session emacs